// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXtjguzjWtbHbh5c7lpfYlcIWffXUVQU',
    appId: '1:962986428230:web:1ff8e8d24769c3f0510747',
    messagingSenderId: '962986428230',
    projectId: 'gearshareapp-f6988',
    authDomain: 'gearshareapp-f6988.firebaseapp.com',
    storageBucket: 'gearshareapp-f6988.firebasestorage.app',
    measurementId: 'G-B59P2JHEV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhGobz4cLqOBd0g-46rfu9INSpeCm-QU',
    appId: '1:962986428230:android:3d6ddd62a57d46a5510747',
    messagingSenderId: '962986428230',
    projectId: 'gearshareapp-f6988',
    storageBucket: 'gearshareapp-f6988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lGBUM-3acrUZjOqsoh18O8vYQvYibdY',
    appId: '1:962986428230:ios:53b9b65cf42eb3cd510747',
    messagingSenderId: '962986428230',
    projectId: 'gearshareapp-f6988',
    storageBucket: 'gearshareapp-f6988.firebasestorage.app',
    iosBundleId: 'com.example.gearshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8lGBUM-3acrUZjOqsoh18O8vYQvYibdY',
    appId: '1:962986428230:ios:53b9b65cf42eb3cd510747',
    messagingSenderId: '962986428230',
    projectId: 'gearshareapp-f6988',
    storageBucket: 'gearshareapp-f6988.firebasestorage.app',
    iosBundleId: 'com.example.gearshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXtjguzjWtbHbh5c7lpfYlcIWffXUVQU',
    appId: '1:962986428230:web:f25ef4b323ac43ff510747',
    messagingSenderId: '962986428230',
    projectId: 'gearshareapp-f6988',
    authDomain: 'gearshareapp-f6988.firebaseapp.com',
    storageBucket: 'gearshareapp-f6988.firebasestorage.app',
    measurementId: 'G-X1QRL4HGSE',
  );
}
